E_branches:
  - "Evt/run_id"
  - "Evt/id"
  - "Evt/trks/trks.E" 
  - "Evt/trks/trks.type"

T_branches:
  - "bdt_trk"
  - "bdt_casc"
  - "coords/mjd"
  - "coords/trackfit_ra"
  - "coords/trackfit_dec"
