E_branches:
  - "Evt/run_id"
  - "Evt/id"
  - "Evt/trks/trks.E" 
  - "Evt/trks/trks.type"
  - "Evt/trks/trks.id"
  - "Evt/trks/trks.t"
  - "Evt/trks/trks.len" 
  - "Evt/trks/trks.lik"
  - "Evt/trks/trks.type"
  - "Evt/trks/trks.rec_type"
  - "Evt/w"
 

T_branches:
  - "bdt_trk"
  - "coords/mjd"
  - "coords/trackfit_ra"
  - "coords/trackfit_dec"
