FileConfig:
  Saveing_Dir: "/pbs/home/a/anayerho/SPS/DataSets/Km3KitProductions/"
  formt : PDF

plots_Dir:
  Saveing_Dir: "/pbs/home/a/anayerho/SPS/Plots/"
  format: png

DataLoading:
  skip_Saving: False
  






