
- name: arca21_bdt
  date_added: '2024-11-10'
  data_type: ROOT
  comment: ' arca21_data_v8.1.1 BDT with coords'
  folder: ''
  path:
    data:
      - /sps/km3net/users/amid/production/arca21/Coords_Merged/v2/datav8.1.1.all.jchain.aashower.dst.bdt_casc.bdt_trk.root  
    data_livetime: []
    muon:
      -  /sps/km3net/users/amid/production/arca21/Coords_Merged/v2/mcv8.1.all.mupage_tuned_100G.sirene.jterbr.jchain.aashower.dst.bdt_casc.bdt_trk.root
    muon_livetime: []
    neutrino:
      - /sps/km3net/users/amid/production/arca21/Coords_Merged/v2/mcv8.1.all.gsg_anue-CCHEDIS_1e2-1e8GeV.sirene.jterbr.jchain.aashower.dst.bdt_casc.bdt_trk.root
      - /sps/km3net/users/amid/production/arca21/Coords_Merged/v2/mcv8.1.all.gsg_anue-NCHEDIS_1e2-1e8GeV.sirene.jterbr.jchain.aashower.dst.bdt_casc.bdt_trk.root
      - /sps/km3net/users/amid/production/arca21/Coords_Merged/v2/mcv8.1.all.gsg_anumu-CCHEDIS_1e2-1e8GeV.sirene.jterbr.jchain.aashower.dst.bdt_casc.bdt_trk.root
      - /sps/km3net/users/amid/production/arca21/Coords_Merged/v2/mcv8.1.all.gsg_anumu-NCHEDIS_1e2-1e8GeV.sirene.jterbr.jchain.aashower.dst.bdt_casc.bdt_trk.root
      - /sps/km3net/users/amid/production/arca21/Coords_Merged/v2/mcv8.1.all.gsg_anutau-CCHEDIS-muon_1e2-1e8GeV.sirene.jterbr.jchain.aashower.dst.bdt_casc.bdt_trk.root
      - /sps/km3net/users/amid/production/arca21/Coords_Merged/v2/mcv8.1.all.gsg_anutau-CCHEDIS-shower_1e2-1e8GeV.sirene.jterbr.jchain.aashower.dst.bdt_casc.bdt_trk.root
      - /sps/km3net/users/amid/production/arca21/Coords_Merged/v2/mcv8.1.all.gsg_anutau-NCHEDIS_1e2-1e8GeV.sirene.jterbr.jchain.aashower.dst.bdt_casc.bdt_trk.root
      - /sps/km3net/users/amid/production/arca21/Coords_Merged/v2/mcv8.1.all.gsg_nue-CCHEDIS_1e2-1e8GeV.sirene.jterbr.jchain.aashower.dst.bdt_casc.bdt_trk.root
      - /sps/km3net/users/amid/production/arca21/Coords_Merged/v2/mcv8.1.all.gsg_nue-NCHEDIS_1e2-1e8GeV.sirene.jterbr.jchain.aashower.dst.bdt_casc.bdt_trk.root
      - /sps/km3net/users/amid/production/arca21/Coords_Merged/v2/mcv8.1.all.gsg_numu-CCHEDIS_1e2-1e8GeV.sirene.jterbr.jchain.aashower.dst.bdt_casc.bdt_trk.root
      - /sps/km3net/users/amid/production/arca21/Coords_Merged/v2/mcv8.1.all.gsg_numu-NCHEDIS_1e2-1e8GeV.sirene.jterbr.jchain.aashower.dst.bdt_casc.bdt_trk.root
      - /sps/km3net/users/amid/production/arca21/Coords_Merged/v2/mcv8.1.all.gsg_nutau-CCHEDIS-muon_1e2-1e8GeV.sirene.jterbr.jchain.aashower.dst.bdt_casc.bdt_trk.root
      - /sps/km3net/users/amid/production/arca21/Coords_Merged/v2/mcv8.1.all.gsg_nutau-CCHEDIS-shower_1e2-1e8GeV.sirene.jterbr.jchain.aashower.dst.bdt_casc.bdt_trk.root
      - /sps/km3net/users/amid/production/arca21/Coords_Merged/v2/mcv8.1.all.gsg_nutau-NCHEDIS_1e2-1e8GeV.sirene.jterbr.jchain.aashower.dst.bdt_casc.bdt_trk.root
    neutrino_livetime: []



- name: arca21_dst
  date_added: '2024-11-10'
  data_type: ROOT
  comment: ' arca21_data_v8.1.1 DST'
  folder: ''
  path:
    data:
      - /sps/km3net/repo/data_processing/tag/v8.1/data_processing/prod/dst/KM3NeT_00000133/v4/merged_all/datav8.1.1.all.jchain.aashower.dst.root   
    data_livetime: []
    muon:
      - /sps/km3net/repo/data_processing/tag/v8.1/data_processing/prod/dst/KM3NeT_00000133/v4/merged_all/mcv8.1.all.mupage_tuned_100G.sirene.jterbr.jchain.aashower.dst.root
    muon_livetime: []
    neutrino:
      - /sps/km3net/repo/data_processing/tag/v8.1/data_processing/prod/dst/KM3NeT_00000133/v4/merged_all/mcv8.1.all.gsg_nue-CCHEDIS_1e2-1e8GeV.sirene.jterbr.jchain.aashower.dst.root
      - /sps/km3net/repo/data_processing/tag/v8.1/data_processing/prod/dst/KM3NeT_00000133/v4/merged_all/mcv8.1.all.gsg_anue-CCHEDIS_1e2-1e8GeV.sirene.jterbr.jchain.aashower.dst.root           
      - /sps/km3net/repo/data_processing/tag/v8.1/data_processing/prod/dst/KM3NeT_00000133/v4/merged_all/mcv8.1.all.gsg_nue-NCHEDIS_1e2-1e8GeV.sirene.jterbr.jchain.aashower.dst.root
      - /sps/km3net/repo/data_processing/tag/v8.1/data_processing/prod/dst/KM3NeT_00000133/v4/merged_all/mcv8.1.all.gsg_anue-NCHEDIS_1e2-1e8GeV.sirene.jterbr.jchain.aashower.dst.root           
      - /sps/km3net/repo/data_processing/tag/v8.1/data_processing/prod/dst/KM3NeT_00000133/v4/merged_all/mcv8.1.all.gsg_numu-CCHEDIS_1e2-1e8GeV.sirene.jterbr.jchain.aashower.dst.root
      - /sps/km3net/repo/data_processing/tag/v8.1/data_processing/prod/dst/KM3NeT_00000133/v4/merged_all/mcv8.1.all.gsg_anumu-CCHEDIS_1e2-1e8GeV.sirene.jterbr.jchain.aashower.dst.root          
      - /sps/km3net/repo/data_processing/tag/v8.1/data_processing/prod/dst/KM3NeT_00000133/v4/merged_all/mcv8.1.all.gsg_numu-NCHEDIS_1e2-1e8GeV.sirene.jterbr.jchain.aashower.dst.root
      - /sps/km3net/repo/data_processing/tag/v8.1/data_processing/prod/dst/KM3NeT_00000133/v4/merged_all/mcv8.1.all.gsg_anumu-NCHEDIS_1e2-1e8GeV.sirene.jterbr.jchain.aashower.dst.root          
      - /sps/km3net/repo/data_processing/tag/v8.1/data_processing/prod/dst/KM3NeT_00000133/v4/merged_all/mcv8.1.all.gsg_nutau-CCHEDIS-muon_1e2-1e8GeV.sirene.jterbr.jchain.aashower.dst.root
      - /sps/km3net/repo/data_processing/tag/v8.1/data_processing/prod/dst/KM3NeT_00000133/v4/merged_all/mcv8.1.all.gsg_anutau-CCHEDIS-muon_1e2-1e8GeV.sirene.jterbr.jchain.aashower.dst.root    
      - /sps/km3net/repo/data_processing/tag/v8.1/data_processing/prod/dst/KM3NeT_00000133/v4/merged_all/mcv8.1.all.gsg_nutau-CCHEDIS-shower_1e2-1e8GeV.sirene.jterbr.jchain.aashower.dst.root
      - /sps/km3net/repo/data_processing/tag/v8.1/data_processing/prod/dst/KM3NeT_00000133/v4/merged_all/mcv8.1.all.gsg_anutau-CCHEDIS-shower_1e2-1e8GeV.sirene.jterbr.jchain.aashower.dst.root 
      - /sps/km3net/repo/data_processing/tag/v8.1/data_processing/prod/dst/KM3NeT_00000133/v4/merged_all/mcv8.1.all.gsg_nutau-NCHEDIS_1e2-1e8GeV.sirene.jterbr.jchain.aashower.dst.root
      - /sps/km3net/repo/data_processing/tag/v8.1/data_processing/prod/dst/KM3NeT_00000133/v4/merged_all/mcv8.1.all.gsg_anutau-NCHEDIS_1e2-1e8GeV.sirene.jterbr.jchain.aashower.dst.root        

    neutrino_livetime: []





