columns:
  run_id:           [RUN_ID,   D,   None]
  
  trks.E_0 :        [ENERGY,   E,   None]

  id:               [EVENT_ID, D,   None]
  Type:             [TYPE,     D,   None]
  ra_values:        [RA,       E,   (180 / np.pi)"]
  dec_values:       [DEC,      E,   (180 / np.pi)"]
  time_values:      [TIME,     D,   None]


header:
  XTENSION: BINTABLE
  BITPIX: 8
  NAXIS: 2
  NAXIS1: 154
  NAXIS2: len(df)
  TFIELDS: len(columns)
  DATE: NONE
  DATE-OBS: NONE
  DATE-END: NONE
  TELESCOP: Km3NeT
  INSTRUME: Arca
  OBSERVER: Arca21
  EQUINOX: 2000.0
  RADECSYS: FK5
  MJDREFI: 0.0
  MJDREFF: 0.00074287037037037
  TIMEUNIT: s
  TIMESYS: TT
  DSTYP2: TIME
  DSUNI2: d
  DSTYP4: ENERGY
  DSUNI4: MeV
  DSVAL4: 10000:2000000

