columns:
  run_id:          [RUN_ID,   D, " " , "1"]
  id:              [EVENT_ID, D, " " , "1"]
  Type:            [TYPE,     D, " ", "1"]
  ra_values:       [RA,       E, deg ,(57.2957795131)]
  dec_values:      [DEC,     E,  deg ,(57.2957795131)]
  trks.E_0:        [ENERGY,  E,  GeV,  "1"]
  mjd:             [TIME,    D,  s,    "1"]


 'trks.type_0', 'trks.type_1',
       'trks.id_0', 'trks.id_1', 'trks.t_0', 'trks.t_1', 'trks.len_0',
       'trks.len_1', 'trks.lik_0', 'trks.lik_1', 'trks.rec_type_0',
       'trks.rec_type_1', 'bdt_trk_0', 'bdt_trk_1', 'mjd', 'trackfit_ra',
       'trackfit_dec'],
      dtype='object')



event_header:
  XTENSION: BINTABLE
  BITPIX: 8
  NAXIS: 2
  NAXIS1: 154     

  PCOUNT: 0
  GCOUNT : 1
  TELESCOP: KM3NeT
  INSTRUME: ARCA
  EQUINOX: 2000.0
  RADECSYS: FK5
  DATE: NONE       
  DATE-OBS: NONE   
  DATE-END: None   
  ORIGIN: INFN
  EXTNAME: EVENTS
  HDUCLASS: OGIP
  HDUCLAS1: EVENTS
  HDUCLAS2: ALL
  TSTART  : NONE                                       
  TSTOP   : NONE                                      
  MJDREFI :      0.0                                   
  MJDREFF :      0.0    
  TIMEUNIT:   s 
  TIMESYS:    TT



GTI_header:
  XTENSION: BINTABLE
  BITPIX: 8
  NAXIS: 2
  NAXIS1: 154
  PCOUNT: 0
  GCOUNT : 1
  TELESCOP: KM3NeT
  INSTRUME: ARCA
  EQUINOX: 2000.0
  RADECSYS: FK5
  DATE: NONE       
  DATE-OBS: NONE    
  DATE-END: None    
  ORIGIN: INFN
  EXTNAME: GTI
  HDUCLASS: OGIP
  HDUCLAS1: GTI
  HDUCLAS2: ALL
  TSTART  : NONE                                            
  TSTOP   : NONE                                       
  MJDREFI :  0.0                                           
  MJDREFF :  0.0     
  TIMEUNIT:   s 
  TIMESYS:    TT
  TIMEREF : 'LOCAL '


Primary:
  SIMPLE: T
  BITPIX: 8
  NAXIS: 0
  EXTEND: T