columns:
  run_id:          [RUN_ID,   D, " " , "1"]
  id:              [EVENT_ID, D, " " , "1"]
  trks.rec_type_0:            [TYPE,     D, " ", "1"]
  trackfit_ra:     [RA,       E, deg ,(57.2957795131)]
  trackfit_dec:    [DEC,     E,  deg ,(57.2957795131)]
  trks.E_0:        [ENERGY,  E,  GeV,  "1"]
  mjd:             [TIME,    D,  s,    "1"]



event_header:
  XTENSION: BINTABLE
  BITPIX: 8
  NAXIS: 2
  NAXIS1: 154     

  PCOUNT: 0
  GCOUNT : 1
  TELESCOP: KM3NeT
  INSTRUME: ARCA
  EQUINOX: 2000.0
  RADECSYS: FK5
  DATE: NONE       
  DATE-OBS: NONE   
  DATE-END: None   
  ORIGIN: INFN
  EXTNAME: EVENTS
  HDUCLASS: OGIP
  HDUCLAS1: EVENTS
  HDUCLAS2: ALL
  TSTART  : NONE                                       
  TSTOP   : NONE                                      
  MJDREFI :      0.0                                   
  MJDREFF :      0.0    
  TIMEUNIT:   s 
  TIMESYS:    TT



GTI_header:
  XTENSION: BINTABLE
  BITPIX: 8
  NAXIS: 2
  NAXIS1: 154
  PCOUNT: 0
  GCOUNT : 1
  TELESCOP: KM3NeT
  INSTRUME: ARCA
  EQUINOX: 2000.0
  RADECSYS: FK5
  DATE: NONE       
  DATE-OBS: NONE    
  DATE-END: None    
  ORIGIN: INFN
  EXTNAME: GTI
  HDUCLASS: OGIP
  HDUCLAS1: GTI
  HDUCLAS2: ALL
  TSTART  : NONE                                            
  TSTOP   : NONE                                       
  MJDREFI :  0.0                                           
  MJDREFF :  0.0     
  TIMEUNIT:   s 
  TIMESYS:    TT
  TIMEREF : 'LOCAL '


Primary:
  SIMPLE: T
  BITPIX: 8
  NAXIS: 0
  EXTEND: T