Variables:


columns:
  ENERGY:    [E,    trks.E_0, None]
  RUN_ID:    [D,    run_id, None]
  EVENT_ID:  [D, id, None]
  TYPE:      [D, Type, None]
  RA:        [E, ra_values, "df_column * (180 / np.pi)"]
  DEC:       [E, dec_values, "df_column * (180 / np.pi)"]
  TIME:      [D, time_values, None]

header:
  XTENSION: BINTABLE
  BITPIX: 8
  NAXIS: 2
  NAXIS1: 154
  NAXIS2: len(df)
  TFIELDS: len(columns)
  DATE: NONE
  DATE-OBS: NONE
  DATE-END: NONE
  TELESCOP: Km3NeT
  INSTRUME: Arca
  OBSERVER: Arca21
  EQUINOX: 2000.0
  RADECSYS: FK5
  MJDREFI: 0.0
  MJDREFF: 0.00074287037037037
  TIMEUNIT: s
  TIMESYS: TT
  DSTYP2: TIME
  DSUNI2: d
  DSTYP4: ENERGY
  DSUNI4: MeV
  DSVAL4: 10000:2000000

